### ISSUE TITLE
[win10] FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by Forecaster** [hubbcaps/gazee#56]
#### Bug Report

The following error occurred during comic scan on application start. It successfully found a number of comics before throwing the error.

win10
Python 3.6.5

 ```
$ python Gazee.py
Gazee has started
Comic Scan Started
Traceback (most recent call last):
  File "C:\Users\Forecaster\AppData\Local\Programs\Python\Python36\lib\site-packages\rarfile.py", line 2813, in custom_popen
    creationflags=creationflags)
  File "C:\Users\Forecaster\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Forecaster\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Gazee.py", line 207, in <module>
    main()
  File "Gazee.py", line 202, in main
    scanner.rescan_db()
  File "C:\gazee\gazee\comicscan.py", line 441, in rescan_db
    self.db_builder()
  File "C:\gazee\gazee\comicscan.py", line 354, in db_builder
    self.build_unpack_comic(f)
  File "C:\gazee\gazee\comicscan.py", line 77, in build_unpack_comic
    opened_rar.extractall(os.path.join(gazee.TEMP_DIR, "build"))
  File "C:\Users\Forecaster\AppData\Local\Programs\Python\Python36\lib\site-packages\rarfile.py", line 820, in extractall
    self._extract(fnlist, path, pwd)
  File "C:\Users\Forecaster\AppData\Local\Programs\Python\Python36\lib\site-packages\rarfile.py", line 885, in _extract
    p = custom_popen(cmd)
  File "C:\Users\Forecaster\AppData\Local\Programs\Python\Python36\lib\site-packages\rarfile.py", line 2816, in custom_popen
    raise RarCannotExec("Unrar not installed? (rarfile.UNRAR_TOOL=%r)" % UNRAR_TOOL)
rarfile.RarCannotExec: Unrar not installed? (rarfile.UNRAR_TOOL='unrar')
```

**Comment by MasterOdin** [comment]
You'll need to install [Unrar](https://www.rarlab.com/rar_add.htm) and then place it somewhere on your system path, or you could use [Chocolatey](https://chocolatey.org/) to install it (which is what I personally did): `choco install unrar`.

More instructions in https://github.com/hubbcaps/gazee/wiki/Windows-Install-Guide#unrar-install.
