### ISSUE TITLE
ImportError: No module named 'cheroot'

### ISSUE THREAD

**Issue by barbequesauce** [hubbcaps/gazee#57]
#### Bug Report

New install on Raspbian Jessie. Traceback when starting up first time. pip3 install of requirements was successful. Output from pip3 list attached below.

```
Traceback (most recent call last):
  File "Gazee.py", line 21, in <module>
    import cherrypy
  File "/usr/local/lib/python3.4/dist-packages/cherrypy/__init__.py", line 76, in <module>
    from cherrypy import _cprequest
  File "/usr/local/lib/python3.4/dist-packages/cherrypy/_cprequest.py", line 10, in <module>
    from cherrypy import _cpreqbody, _cpconfig
  File "/usr/local/lib/python3.4/dist-packages/cherrypy/_cpreqbody.py", line 135, in <module>
    import cheroot.server
ImportError: No module named 'cheroot'
```

Linux <<hostname>> 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l GNU/Linux
Python 3.4.2 (default, Sep 26 2018, 07:16:01) 
[GCC 4.9.2] on linux
Gazee commit c759ea9

pip list: 
```
cffi (0.8.6) 
chardet (2.3.0) 
CherryPy (11.0.0)
codebug-i2c-tether (0.2.3) 
codebug-tether (0.7.0) 
colorama (0.3.2) 
cryptography (0.6.1) 
Flask (0.10.1)
gitdb2 (2.0.5) 
GitPython (2.1.5) 
gpiozero (1.4.0) 
html5lib (0.999) 
itsdangerous (0.24)
Jinja2 (2.7.3) 
Mako (1.0.7) 
MarkupSafe (0.23)
mcpi (0.1.1) 
numpy (1.8.2) 
olefile (0.46)
patool (1.12)
peewee (3.6.4) 
pgzero (1.1)
picamera (1.13)
picraft (1.0)
pifacecommon (4.2.1) 
pifacedigitalio (3.1.0) 
pigpio (1.35)
Pillow (2.6.1) 
pip (1.5.6) 
ply (3.4)
pycparser (2.10)
pygame (1.9.2a0)
Pygments (2.2.0) 
pygobject (3.14.0)
pyinotify (0.9.4) 
pyOpenSSL (0.14)
pyserial (2.6)
python-apt (0.9.3.12)
python-debian (0.1.27)
rarfile (3.0)
requests (2.4.3) 
RPi.GPIO (0.6.3) 
RTIMULib (7.2.1) 
sense-emu (1.0)
sense-hat (2.2.0) 
setuptools (5.5.1) 
six (1.8.0) 
smbus (1.1)
smmap2 (2.0.5) 
spidev (3.0)
sqlite-web (0.3.3)
twython (3.1.2)
urllib3 (1.9.1)
Werkzeug (0.9.6)
wheel (0.24.0)
xmltodict (0.11.0)
```

**Comment by barbequesauce** [comment]
Seems newer version of CherryPy doesnt bundle Cheroot or portend. Adding them to the requirements list fixed this. PR incoming.
